import type { Metadata } from "next";
import "./globals.css";
import LayoutWrapper from "@/components/layoutwrapper";
import Script from "next/script";
import { Poppins } from "next/font/google";
import "easymde/dist/easymde.min.css";
import { Toaster } from "@/components/ui/toaster";
import LoadingBar from "@/components/lodingbar";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";
const poppins = Poppins({ weight: "400", subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Project Bin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://kit.fontawesome.com/3635c4cce0.js"
          strategy="afterInteractive"
          crossOrigin="anonymous"></Script>
        <link rel="icon" href="/title.jpg" />
      </head>

      <body className={`${poppins.className} tracking-wide`}>
        <LayoutWrapper>
          <LoadingBar/>
          {children}
          <Toaster />
          <Analytics />
          <SpeedInsights/>
        </LayoutWrapper>
      </body>
    </html>
  );
}
